### ISSUE TITLE
"403 Forbidden" on base installation on "/"

### ISSUE THREAD

**Issue by Psycojoker** [xpd259/gitableHost_yunohost#6]
Hello,

I've tried installing this app on a domain on the path "/" and end up with a "443 forbidden" by nginx. The logs says:

    2016/10/23 22:40:30 [error] 12107#0: *60676 directory index of "/home/yunohost.app/gitable/githost" is forbidden, client: 109.133.29.194, server: neutrinet.be, request: "GET / HTTP/1.1", host: "neutrinet.be"

And if I explicitly specify "index.html" I get:

    2016/10/23 22:44:40 [error] 12107#0: *60694 open() "/home/yunohost.app/gitable/githostindex.html" failed (2: No such file or directory), client: 109.133.29.194, server: neutrinet.be, request: "GET /index.html HTTP/1.1", host: "neutrinet.be"

To fix it I simply add to change:

    alias /home/yunohost.app/gitable/githost ;

To (notice trailing "/"):

    alias /home/yunohost.app/gitable/githost/ ;

You can fix this using "path=${path%/}" in your installation script to handle empty path.

Kind regards,

**Comment by xpd259** [comment]
thank you so much for the feedback, I never really expected anyone to even look at this!
I'm really sorry you encounted a error and I hope this fixes it for you.

**Comment by Psycojoker** [comment]
Don't worry, errors are the life of a project, thanks for doing it!
